name: Latest Hashnode Blog Posts
on:
  schedule:
    # Runs every hour of the day
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGPOSTS"
          feed_list: "https://iano10x.hashnode.dev/rss.xml"
          commit_message: "recent posts section updated"
          
